//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_EMPRESA3_Entities : DbContext
    {
        public BD_EMPRESA3_Entities()
            : base("name=BD_EMPRESA3_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_acao_banner> tb_acao_banner { get; set; }
        public virtual DbSet<tb_analise_pedido_vias_crm> tb_analise_pedido_vias_crm { get; set; }
        public virtual DbSet<tb_analise_spd_conta> tb_analise_spd_conta { get; set; }
        public virtual DbSet<tb_aux_developer> tb_aux_developer { get; set; }
        public virtual DbSet<tb_aux_sbe> tb_aux_sbe { get; set; }
        public virtual DbSet<tb_avaliacao> tb_avaliacao { get; set; }
        public virtual DbSet<tb_banco> tb_banco { get; set; }
        public virtual DbSet<tb_banco_conta_digital> tb_banco_conta_digital { get; set; }
        public virtual DbSet<tb_banner> tb_banner { get; set; }
        public virtual DbSet<tb_black_list> tb_black_list { get; set; }
        public virtual DbSet<tb_black_list_usuario_forma_pagamento> tb_black_list_usuario_forma_pagamento { get; set; }
        public virtual DbSet<tb_bloqueio_cartao> tb_bloqueio_cartao { get; set; }
        public virtual DbSet<tb_boleto> tb_boleto { get; set; }
        public virtual DbSet<tb_campanha> tb_campanha { get; set; }
        public virtual DbSet<tb_canal> tb_canal { get; set; }
        public virtual DbSet<tb_chave_pix> tb_chave_pix { get; set; }
        public virtual DbSet<tb_cidade> tb_cidade { get; set; }
        public virtual DbSet<tb_conta> tb_conta { get; set; }
        public virtual DbSet<tb_crm_motivo_relacionamento> tb_crm_motivo_relacionamento { get; set; }
        public virtual DbSet<tb_crm_protocolo_atendimento> tb_crm_protocolo_atendimento { get; set; }
        public virtual DbSet<tb_crm_relacionamento> tb_crm_relacionamento { get; set; }
        public virtual DbSet<tb_crm_relacionamento_arquivos> tb_crm_relacionamento_arquivos { get; set; }
        public virtual DbSet<tb_crm_relacionamento_usr_atribuido> tb_crm_relacionamento_usr_atribuido { get; set; }
        public virtual DbSet<tb_crm_situacao_relacionamento> tb_crm_situacao_relacionamento { get; set; }
        public virtual DbSet<tb_crm_situacao_relacionamento_usr_atribuido> tb_crm_situacao_relacionamento_usr_atribuido { get; set; }
        public virtual DbSet<tb_crm_tipo_relacionamento> tb_crm_tipo_relacionamento { get; set; }
        public virtual DbSet<tb_cupom> tb_cupom { get; set; }
        public virtual DbSet<tb_cupom_categoria_loja> tb_cupom_categoria_loja { get; set; }
        public virtual DbSet<tb_cupom_loja> tb_cupom_loja { get; set; }
        public virtual DbSet<tb_cupom_oferta> tb_cupom_oferta { get; set; }
        public virtual DbSet<tb_cupom_usuario> tb_cupom_usuario { get; set; }
        public virtual DbSet<tb_deletar> tb_deletar { get; set; }
        public virtual DbSet<tb_diagnostico_contas_dock> tb_diagnostico_contas_dock { get; set; }
        public virtual DbSet<tb_dicionario_erro> tb_dicionario_erro { get; set; }
        public virtual DbSet<tb_duvida> tb_duvida { get; set; }
        public virtual DbSet<tb_duvida_assunto> tb_duvida_assunto { get; set; }
        public virtual DbSet<tb_duvida_assunto_revenda> tb_duvida_assunto_revenda { get; set; }
        public virtual DbSet<tb_duvida_revenda> tb_duvida_revenda { get; set; }
        public virtual DbSet<tb_erro_abertura_conta> tb_erro_abertura_conta { get; set; }
        public virtual DbSet<tb_erro_sistema> tb_erro_sistema { get; set; }
        public virtual DbSet<tb_estado_civil> tb_estado_civil { get; set; }
        public virtual DbSet<tb_estorno_pedido> tb_estorno_pedido { get; set; }
        public virtual DbSet<tb_estorno_pedido_item> tb_estorno_pedido_item { get; set; }
        public virtual DbSet<tb_estudante_complemento> tb_estudante_complemento { get; set; }
        public virtual DbSet<tb_etapa_via> tb_etapa_via { get; set; }
        public virtual DbSet<tb_etapa_via_rejeicao> tb_etapa_via_rejeicao { get; set; }
        public virtual DbSet<tb_faq> tb_faq { get; set; }
        public virtual DbSet<tb_fastcash_phill> tb_fastcash_phill { get; set; }
        public virtual DbSet<tb_fila_analise_revalidacao> tb_fila_analise_revalidacao { get; set; }
        public virtual DbSet<tb_fila_envio_email> tb_fila_envio_email { get; set; }
        public virtual DbSet<tb_fila_notificacao> tb_fila_notificacao { get; set; }
        public virtual DbSet<tb_fluxo_etapa_via> tb_fluxo_etapa_via { get; set; }
        public virtual DbSet<tb_forma_pagamento> tb_forma_pagamento { get; set; }
        public virtual DbSet<tb_formulario_pergunta> tb_formulario_pergunta { get; set; }
        public virtual DbSet<tb_formulario_resposta_usuario> tb_formulario_resposta_usuario { get; set; }
        public virtual DbSet<tb_gateway> tb_gateway { get; set; }
        public virtual DbSet<tb_gateway_fastcash> tb_gateway_fastcash { get; set; }
        public virtual DbSet<tb_ged_pedido> tb_ged_pedido { get; set; }
        public virtual DbSet<tb_ged_pedido_cartao> tb_ged_pedido_cartao { get; set; }
        public virtual DbSet<tb_ged_pedido_cash_in> tb_ged_pedido_cash_in { get; set; }
        public virtual DbSet<tb_ged_revalidacao> tb_ged_revalidacao { get; set; }
        public virtual DbSet<tb_ged_temporario> tb_ged_temporario { get; set; }
        public virtual DbSet<tb_historico_pedido_pagamento_picpay> tb_historico_pedido_pagamento_picpay { get; set; }
        public virtual DbSet<tb_historico_requisicao_via> tb_historico_requisicao_via { get; set; }
        public virtual DbSet<tb_importacao_adyen> tb_importacao_adyen { get; set; }
        public virtual DbSet<tb_instrucao_boleto> tb_instrucao_boleto { get; set; }
        public virtual DbSet<tb_integracao> tb_integracao { get; set; }
        public virtual DbSet<tb_integracao_historico> tb_integracao_historico { get; set; }
        public virtual DbSet<tb_integracao_parametro_notificacao> tb_integracao_parametro_notificacao { get; set; }
        public virtual DbSet<tb_itinerarios> tb_itinerarios { get; set; }
        public virtual DbSet<tb_EMPRESA3lometros> tb_EMPRESA3lometros { get; set; }
        public virtual DbSet<tb_EMPRESA3lometros_config> tb_EMPRESA3lometros_config { get; set; }
        public virtual DbSet<tb_EMPRESA3lometros_expirados> tb_EMPRESA3lometros_expirados { get; set; }
        public virtual DbSet<tb_EMPRESA3lometros_integracoes_diarias> tb_EMPRESA3lometros_integracoes_diarias { get; set; }
        public virtual DbSet<tb_EMPRESA3lometros_resgate> tb_EMPRESA3lometros_resgate { get; set; }
        public virtual DbSet<tb_linha_itinerario> tb_linha_itinerario { get; set; }
        public virtual DbSet<tb_linha_paradas> tb_linha_paradas { get; set; }
        public virtual DbSet<tb_log_alt_telefone> tb_log_alt_telefone { get; set; }
        public virtual DbSet<tb_log_black_list> tb_log_black_list { get; set; }
        public virtual DbSet<tb_log_black_list_usuario_forma_pagamento> tb_log_black_list_usuario_forma_pagamento { get; set; }
        public virtual DbSet<tb_log_conciliacao_fastcash> tb_log_conciliacao_fastcash { get; set; }
        public virtual DbSet<tb_log_doacao> tb_log_doacao { get; set; }
        public virtual DbSet<tb_log_dock> tb_log_dock { get; set; }
        public virtual DbSet<tb_log_dock2> tb_log_dock2 { get; set; }
        public virtual DbSet<tb_log_email> tb_log_email { get; set; }
        public virtual DbSet<tb_log_erro_abertura_conta> tb_log_erro_abertura_conta { get; set; }
        public virtual DbSet<tb_log_itau_pix> tb_log_itau_pix { get; set; }
        public virtual DbSet<tb_log_notificacao_gateway> tb_log_notificacao_gateway { get; set; }
        public virtual DbSet<tb_log_pedido> tb_log_pedido { get; set; }
        public virtual DbSet<tb_log_pedido_estocagem> tb_log_pedido_estocagem { get; set; }
        public virtual DbSet<tb_log_pedido_item> tb_log_pedido_item { get; set; }
        public virtual DbSet<tb_log_pedido_item_cancelamento_rv> tb_log_pedido_item_cancelamento_rv { get; set; }
        public virtual DbSet<tb_log_registro> tb_log_registro { get; set; }
        public virtual DbSet<tb_log_sbe> tb_log_sbe { get; set; }
        public virtual DbSet<tb_log_sms> tb_log_sms { get; set; }
        public virtual DbSet<tb_log_terminal> tb_log_terminal { get; set; }
        public virtual DbSet<tb_log_usuario_alteracao> tb_log_usuario_alteracao { get; set; }
        public virtual DbSet<tb_log_usuario_cartao> tb_log_usuario_cartao { get; set; }
        public virtual DbSet<tb_log_usuario_programa_fidelidade> tb_log_usuario_programa_fidelidade { get; set; }
        public virtual DbSet<tb_log_usuario_revenda> tb_log_usuario_revenda { get; set; }
        public virtual DbSet<tb_log_usuario_revenda_comissao> tb_log_usuario_revenda_comissao { get; set; }
        public virtual DbSet<tb_log_usuario_revenda_limite> tb_log_usuario_revenda_limite { get; set; }
        public virtual DbSet<tb_log_usuario_revenda_suspenso> tb_log_usuario_revenda_suspenso { get; set; }
        public virtual DbSet<tb_menu_adm> tb_menu_adm { get; set; }
        public virtual DbSet<tb_motivo_baixa> tb_motivo_baixa { get; set; }
        public virtual DbSet<tb_municipio_SBE> tb_municipio_SBE { get; set; }
        public virtual DbSet<tb_nacionalidade> tb_nacionalidade { get; set; }
        public virtual DbSet<tb_notificacao> tb_notificacao { get; set; }
        public virtual DbSet<tb_ofertas> tb_ofertas { get; set; }
        public virtual DbSet<tb_ofertas_categoria> tb_ofertas_categoria { get; set; }
        public virtual DbSet<tb_ofertas_loja> tb_ofertas_loja { get; set; }
        public virtual DbSet<tb_operadora> tb_operadora { get; set; }
        public virtual DbSet<tb_operadora_acerto> tb_operadora_acerto { get; set; }
        public virtual DbSet<tb_operadora_banco_conta> tb_operadora_banco_conta { get; set; }
        public virtual DbSet<tb_operadora_cidade> tb_operadora_cidade { get; set; }
        public virtual DbSet<tb_operadora_empresa> tb_operadora_empresa { get; set; }
        public virtual DbSet<tb_operadora_empresa_tipo_cartao> tb_operadora_empresa_tipo_cartao { get; set; }
        public virtual DbSet<tb_operadora_forma_pagamento_gateway> tb_operadora_forma_pagamento_gateway { get; set; }
        public virtual DbSet<tb_operadora_linha> tb_operadora_linha { get; set; }
        public virtual DbSet<tb_operadora_mapa_params> tb_operadora_mapa_params { get; set; }
        public virtual DbSet<tb_operadora_mensagem> tb_operadora_mensagem { get; set; }
        public virtual DbSet<tb_operadora_parceiro_logistico> tb_operadora_parceiro_logistico { get; set; }
        public virtual DbSet<tb_operadora_tipo_canal> tb_operadora_tipo_canal { get; set; }
        public virtual DbSet<tb_operadora_versao_api> tb_operadora_versao_api { get; set; }
        public virtual DbSet<tb_orgao_emissor> tb_orgao_emissor { get; set; }
        public virtual DbSet<tb_pagamento_pedido_parcelado> tb_pagamento_pedido_parcelado { get; set; }
        public virtual DbSet<tb_paradas> tb_paradas { get; set; }
        public virtual DbSet<tb_param_atualizacao_mapa> tb_param_atualizacao_mapa { get; set; }
        public virtual DbSet<tb_param_estocagem_integracao> tb_param_estocagem_integracao { get; set; }
        public virtual DbSet<tb_parameto_itau> tb_parameto_itau { get; set; }
        public virtual DbSet<tb_parametro> tb_parametro { get; set; }
        public virtual DbSet<tb_parametro_anti_fraude> tb_parametro_anti_fraude { get; set; }
        public virtual DbSet<tb_parametro_cashback> tb_parametro_cashback { get; set; }
        public virtual DbSet<tb_parametro_cashdeal> tb_parametro_cashdeal { get; set; }
        public virtual DbSet<tb_parametro_comissao> tb_parametro_comissao { get; set; }
        public virtual DbSet<tb_parametro_email> tb_parametro_email { get; set; }
        public virtual DbSet<tb_parametro_parcelamento> tb_parametro_parcelamento { get; set; }
        public virtual DbSet<tb_parametro_pix_wso> tb_parametro_pix_wso { get; set; }
        public virtual DbSet<tb_parametro_revenda_comissao> tb_parametro_revenda_comissao { get; set; }
        public virtual DbSet<tb_parametro_rv> tb_parametro_rv { get; set; }
        public virtual DbSet<tb_parametro_tentativa_most> tb_parametro_tentativa_most { get; set; }
        public virtual DbSet<tb_parametro_terceiro> tb_parametro_terceiro { get; set; }
        public virtual DbSet<tb_parceiro_logistico> tb_parceiro_logistico { get; set; }
        public virtual DbSet<tb_pedido> tb_pedido { get; set; }
        public virtual DbSet<tb_pedido_atm> tb_pedido_atm { get; set; }
        public virtual DbSet<tb_pedido_cash_in> tb_pedido_cash_in { get; set; }
        public virtual DbSet<tb_pedido_entrega> tb_pedido_entrega { get; set; }
        public virtual DbSet<tb_pedido_item> tb_pedido_item { get; set; }
        public virtual DbSet<tb_pedido_item_cartao> tb_pedido_item_cartao { get; set; }
        public virtual DbSet<tb_pedido_pagamento_picpay> tb_pedido_pagamento_picpay { get; set; }
        public virtual DbSet<tb_pedido_pagamento_pix> tb_pedido_pagamento_pix { get; set; }
        public virtual DbSet<tb_pedido_revenda> tb_pedido_revenda { get; set; }
        public virtual DbSet<tb_pedido_rv> tb_pedido_rv { get; set; }
        public virtual DbSet<tb_perfil> tb_perfil { get; set; }
        public virtual DbSet<tb_perfil_sub_menu_adm> tb_perfil_sub_menu_adm { get; set; }
        public virtual DbSet<tb_posto> tb_posto { get; set; }
        public virtual DbSet<tb_posto_operadora> tb_posto_operadora { get; set; }
        public virtual DbSet<tb_programa_fidelidade> tb_programa_fidelidade { get; set; }
        public virtual DbSet<tb_programa_fidelidade_resgate> tb_programa_fidelidade_resgate { get; set; }
        public virtual DbSet<tb_quadro_horario> tb_quadro_horario { get; set; }
        public virtual DbSet<tb_recarga_automatica> tb_recarga_automatica { get; set; }
        public virtual DbSet<tb_recarga_programada> tb_recarga_programada { get; set; }
        public virtual DbSet<tb_rel_liq_cobranca> tb_rel_liq_cobranca { get; set; }
        public virtual DbSet<tb_remessa_cobranca> tb_remessa_cobranca { get; set; }
        public virtual DbSet<tb_requisicao_qrcode> tb_requisicao_qrcode { get; set; }
        public virtual DbSet<tb_requisicao_via> tb_requisicao_via { get; set; }
        public virtual DbSet<tb_servico> tb_servico { get; set; }
        public virtual DbSet<tb_status_conta> tb_status_conta { get; set; }
        public virtual DbSet<tb_status_conta_dock> tb_status_conta_dock { get; set; }
        public virtual DbSet<tb_status_entrega> tb_status_entrega { get; set; }
        public virtual DbSet<tb_status_pedido> tb_status_pedido { get; set; }
        public virtual DbSet<tb_status_pedido_item> tb_status_pedido_item { get; set; }
        public virtual DbSet<tb_status_pedido_pagamento_picpay> tb_status_pedido_pagamento_picpay { get; set; }
        public virtual DbSet<tb_status_pedido_pagamento_pix> tb_status_pedido_pagamento_pix { get; set; }
        public virtual DbSet<tb_status_requisicao_via> tb_status_requisicao_via { get; set; }
        public virtual DbSet<tb_sub_menu_adm> tb_sub_menu_adm { get; set; }
        public virtual DbSet<tb_tarefa_entrega> tb_tarefa_entrega { get; set; }
        public virtual DbSet<tb_taxa_adm> tb_taxa_adm { get; set; }
        public virtual DbSet<tb_taxa_operadora_tipo_cartao> tb_taxa_operadora_tipo_cartao { get; set; }
        public virtual DbSet<tb_tentativa_most> tb_tentativa_most { get; set; }
        public virtual DbSet<tb_terminal> tb_terminal { get; set; }
        public virtual DbSet<tb_termo_de_uso> tb_termo_de_uso { get; set; }
        public virtual DbSet<tb_termo_operadora> tb_termo_operadora { get; set; }
        public virtual DbSet<tb_tipo_atualizacao> tb_tipo_atualizacao { get; set; }
        public virtual DbSet<tb_tipo_canal> tb_tipo_canal { get; set; }
        public virtual DbSet<tb_tipo_cartao> tb_tipo_cartao { get; set; }
        public virtual DbSet<tb_tipo_cartao_estoque> tb_tipo_cartao_estoque { get; set; }
        public virtual DbSet<tb_tipo_cartao_forma_pagamento> tb_tipo_cartao_forma_pagamento { get; set; }
        public virtual DbSet<tb_tipo_cartao_tecnologia> tb_tipo_cartao_tecnologia { get; set; }
        public virtual DbSet<tb_tipo_cartao_valor> tb_tipo_cartao_valor { get; set; }
        public virtual DbSet<tb_tipo_documento> tb_tipo_documento { get; set; }
        public virtual DbSet<tb_tipo_email> tb_tipo_email { get; set; }
        public virtual DbSet<tb_tipo_endereco> tb_tipo_endereco { get; set; }
        public virtual DbSet<tb_tipo_log_registro> tb_tipo_log_registro { get; set; }
        public virtual DbSet<tb_tipo_notificacao> tb_tipo_notificacao { get; set; }
        public virtual DbSet<tb_tipo_ocupacao> tb_tipo_ocupacao { get; set; }
        public virtual DbSet<tb_tipo_pedido_item> tb_tipo_pedido_item { get; set; }
        public virtual DbSet<tb_tipo_pedido_item_fluxo_status> tb_tipo_pedido_item_fluxo_status { get; set; }
        public virtual DbSet<tb_tipo_telefone> tb_tipo_telefone { get; set; }
        public virtual DbSet<tb_tipo_transacao> tb_tipo_transacao { get; set; }
        public virtual DbSet<tb_transacao_conta_digital> tb_transacao_conta_digital { get; set; }
        public virtual DbSet<tb_transacao_programa_fidelidade> tb_transacao_programa_fidelidade { get; set; }
        public virtual DbSet<tb_uf> tb_uf { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
        public virtual DbSet<tb_usuario_adm> tb_usuario_adm { get; set; }
        public virtual DbSet<tb_usuario_adm_operadora_empresa> tb_usuario_adm_operadora_empresa { get; set; }
        public virtual DbSet<tb_usuario_banco_conta> tb_usuario_banco_conta { get; set; }
        public virtual DbSet<tb_usuario_banco_conta_chave> tb_usuario_banco_conta_chave { get; set; }
        public virtual DbSet<tb_usuario_cartao> tb_usuario_cartao { get; set; }
        public virtual DbSet<tb_usuario_cartao_credito> tb_usuario_cartao_credito { get; set; }
        public virtual DbSet<tb_usuario_cartao_credito_endereco_cobranca> tb_usuario_cartao_credito_endereco_cobranca { get; set; }
        public virtual DbSet<tb_usuario_cartao_credito_gateway_token> tb_usuario_cartao_credito_gateway_token { get; set; }
        public virtual DbSet<tb_usuario_cartao_favorito_linha> tb_usuario_cartao_favorito_linha { get; set; }
        public virtual DbSet<tb_usuario_conta_corrente> tb_usuario_conta_corrente { get; set; }
        public virtual DbSet<tb_usuario_cupom> tb_usuario_cupom { get; set; }
        public virtual DbSet<tb_usuario_dependente> tb_usuario_dependente { get; set; }
        public virtual DbSet<tb_usuario_dependente_documento_banco> tb_usuario_dependente_documento_banco { get; set; }
        public virtual DbSet<tb_usuario_documento_banco> tb_usuario_documento_banco { get; set; }
        public virtual DbSet<tb_usuario_endereco> tb_usuario_endereco { get; set; }
        public virtual DbSet<tb_usuario_equipamento> tb_usuario_equipamento { get; set; }
        public virtual DbSet<tb_usuario_favorito_linha> tb_usuario_favorito_linha { get; set; }
        public virtual DbSet<tb_usuario_favorito_paradas> tb_usuario_favorito_paradas { get; set; }
        public virtual DbSet<tb_usuario_revenda_comissao> tb_usuario_revenda_comissao { get; set; }
        public virtual DbSet<tb_usuario_revenda_operadora> tb_usuario_revenda_operadora { get; set; }
        public virtual DbSet<tb_usuario_revenda_pre_estocagem> tb_usuario_revenda_pre_estocagem { get; set; }
        public virtual DbSet<tb_usuario_saldo> tb_usuario_saldo { get; set; }
        public virtual DbSet<tb_usuario_solicitacao_exclusao> tb_usuario_solicitacao_exclusao { get; set; }
        public virtual DbSet<tb_usuario_termo_de_uso> tb_usuario_termo_de_uso { get; set; }
        public virtual DbSet<tb_natureza_juridica> tb_natureza_juridica { get; set; }
        public virtual DbSet<vw_bi_acessos_por_dia> vw_bi_acessos_por_dia { get; set; }
        public virtual DbSet<vw_bi_controle_adyen> vw_bi_controle_adyen { get; set; }
        public virtual DbSet<vw_bi_relacionamento_usuario> vw_bi_relacionamento_usuario { get; set; }
        public virtual DbSet<vw_bi_tb_canal> vw_bi_tb_canal { get; set; }
        public virtual DbSet<vw_bi_tb_crm_motivo_relacionamento> vw_bi_tb_crm_motivo_relacionamento { get; set; }
        public virtual DbSet<vw_bi_tb_crm_tipo_relacionamento> vw_bi_tb_crm_tipo_relacionamento { get; set; }
        public virtual DbSet<vw_bi_tb_forma_pagamento> vw_bi_tb_forma_pagamento { get; set; }
        public virtual DbSet<vw_bi_tb_operadora> vw_bi_tb_operadora { get; set; }
        public virtual DbSet<vw_bi_tb_pedido_item> vw_bi_tb_pedido_item { get; set; }
        public virtual DbSet<vw_bi_tb_perfil> vw_bi_tb_perfil { get; set; }
        public virtual DbSet<vw_bi_tb_status_pedido> vw_bi_tb_status_pedido { get; set; }
        public virtual DbSet<vw_bi_tb_status_pedido_item> vw_bi_tb_status_pedido_item { get; set; }
        public virtual DbSet<vw_bi_tb_taxa_operadora_tipo_cartao> vw_bi_tb_taxa_operadora_tipo_cartao { get; set; }
        public virtual DbSet<vw_bi_tb_tipo_cartao> vw_bi_tb_tipo_cartao { get; set; }
        public virtual DbSet<vw_bi_tb_tipo_pedido_item> vw_bi_tb_tipo_pedido_item { get; set; }
        public virtual DbSet<vw_bi_tb_usuario> vw_bi_tb_usuario { get; set; }
        public virtual DbSet<vw_bi_tb_usuario_adm> vw_bi_tb_usuario_adm { get; set; }
        public virtual DbSet<vw_bi_tb_usuario_cartao> vw_bi_tb_usuario_cartao { get; set; }
        public virtual DbSet<vw_bi_tb_usuario_pedido> vw_bi_tb_usuario_pedido { get; set; }
        public virtual DbSet<vw_bi_tb_usuario_pedido_log_mudanca> vw_bi_tb_usuario_pedido_log_mudanca { get; set; }
        public virtual DbSet<vw_bi_tb_usuario_sem_cartao> vw_bi_tb_usuario_sem_cartao { get; set; }
        public virtual DbSet<vw_bi_usuario_cadastro_cartao> vw_bi_usuario_cadastro_cartao { get; set; }
        public virtual DbSet<vw_bi_usuario_pedidos> vw_bi_usuario_pedidos { get; set; }
        public virtual DbSet<vw_bi_vendas> vw_bi_vendas { get; set; }
        public virtual DbSet<vw_Cupom_Disponivel_Usuario> vw_Cupom_Disponivel_Usuario { get; set; }
        public virtual DbSet<vw_integracao> vw_integracao { get; set; }
        public virtual DbSet<vw_EMPRESA3lometros_agrupados> vw_EMPRESA3lometros_agrupados { get; set; }
        public virtual DbSet<vw_Pedidos_AntiFraude> vw_Pedidos_AntiFraude { get; set; }
        public virtual DbSet<vw_Pedidos_AntiFraude_Recarga_Celular> vw_Pedidos_AntiFraude_Recarga_Celular { get; set; }
        public virtual DbSet<vw_Pedidos_AntiFraude_Servicos_Digitais> vw_Pedidos_AntiFraude_Servicos_Digitais { get; set; }
        public virtual DbSet<vw_pedidos_pagar_operadora> vw_pedidos_pagar_operadora { get; set; }
        public virtual DbSet<vw_qnt_cartoes_operadoras> vw_qnt_cartoes_operadoras { get; set; }
        public virtual DbSet<vw_qnt_usuarios_operadoras> vw_qnt_usuarios_operadoras { get; set; }
        public virtual DbSet<vw_SaldoBloqueado> vw_SaldoBloqueado { get; set; }
        public virtual DbSet<vw_ServicosOperadoras> vw_ServicosOperadoras { get; set; }
        public virtual DbSet<vw_status_item_pedido> vw_status_item_pedido { get; set; }
        public virtual DbSet<vw_status_pedido> vw_status_pedido { get; set; }
        public virtual DbSet<vw_UsuarioCartaoOperadora> vw_UsuarioCartaoOperadora { get; set; }
        public virtual DbSet<vw_VendasRevenda> vw_VendasRevenda { get; set; }
        public virtual DbSet<vwListDashBoard> vwListDashBoard { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    }
}
