//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_analise_pedido_vias_crm
    {
        public int cd_analise_pedido { get; set; }
        public Nullable<System.DateTime> dt_analise_pedido { get; set; }
        public string ds_observacao { get; set; }
        public Nullable<int> cd_usuario_adm { get; set; }
        public Nullable<long> cd_pedido { get; set; }
        public Nullable<int> cd_tipo_analise { get; set; }
    }
}
