//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_itinerarios
    {
        public long cd_itinerario { get; set; }
        public string id_itinerario { get; set; }
        public string nu_latitude { get; set; }
        public string nu_longitude { get; set; }
        public Nullable<int> cd_operadora { get; set; }
    }
}
