//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log_itau_pix
    {
        public long cd_pedido { get; set; }
        public string ds_status_itau { get; set; }
        public Nullable<System.DateTime> dt_pagamento_itau { get; set; }
    }
}
