//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log_dock
    {
        public int cd_log_dock { get; set; }
        public string ds_nome { get; set; }
        public string ds_documento { get; set; }
        public Nullable<decimal> vl_saldo { get; set; }
        public Nullable<System.DateTime> dt_saldo { get; set; }
        public Nullable<int> id_conta { get; set; }
        public Nullable<int> id_pessoa { get; set; }
        public string ds_email { get; set; }
    }
}
