//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_param_atualizacao_mapa
    {
        public int cd_param_atualizacao_mapa { get; set; }
        public Nullable<int> cd_tipo_atualizacao { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public Nullable<System.DateTime> dt_ultima_atualizacao { get; set; }
        public Nullable<int> dt_intervalo_atualizacao { get; set; }
        public Nullable<System.DateTime> dt_proxima_atualizacao { get; set; }
        public Nullable<bool> ic_inativo { get; set; }
    }
}
