//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_param_estocagem_integracao
    {
        public int cd_param_estocagem_integracao { get; set; }
        public string ds_sigla_operadora { get; set; }
        public string ds_tipo_estocagem { get; set; }
        public Nullable<decimal> ds_valor_minimo { get; set; }
    }
}
