//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipo_documento
    {
        public short nu_tipo_documento { get; set; }
        public string ds_tipo_documento { get; set; }
        public string ds_documento_banco { get; set; }
        public bool ic_inativo { get; set; }
    }
}
