//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bi_tb_pedido_item
    {
        public long cd_pedido_item { get; set; }
        public long cd_pedido { get; set; }
        public Nullable<long> cd_usuario_cartao { get; set; }
        public Nullable<short> cd_status_pedido_item { get; set; }
    }
}
