//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bi_tb_usuario_pedido_log_mudanca
    {
        public long cd_pedido { get; set; }
        public long cd_pedido_item { get; set; }
        public short cd_status_item_log { get; set; }
        public System.DateTime dt_log { get; set; }
    }
}
