//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bi_tb_forma_pagamento
    {
        public short cd_forma_pagamento { get; set; }
        public string nm_descricao { get; set; }
        public short cd_gateway { get; set; }
    }
}
