//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bi_tb_taxa_operadora_tipo_cartao
    {
        public int cd_taxa_operadora_tipo_cartao { get; set; }
        public int cd_operadora { get; set; }
        public short cd_forma_pagamento { get; set; }
    }
}
