//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_integracao
    {
        public int cod { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> dtanalise { get; set; }
        public string yellow { get; set; }
        public string red { get; set; }
    }
}
