//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_qnt_cartoes_operadoras
    {
        public string nm_fantasia_operadora { get; set; }
        public Nullable<int> TOTAL_CARTOES { get; set; }
    }
}
