//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sptrans_api.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_status_item_pedido
    {
        public short cd_status_pedido_item { get; set; }
        public string nm_descricao { get; set; }
        public string ds_css_icon { get; set; }
        public bool ic_status_pedido_inativo { get; set; }
    }
}
